version: "3.1"

services:
  app:
    container_name: trading_test
    tty: true
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.local
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - redis
    networks:
      - bis_network
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - bis_network


networks:
  bis_network:
    driver: bridge